<?php declare(strict_types=1);

namespace Database\Seeders;

use App\Models\ScrapedTicket;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

use function count;

class ScrapedTicketsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = [
            [
                'platform'       => 'stubhub',
                'external_id'    => 'STUB-MU-LIV-001',
                'title'          => 'Manchester United vs Liverpool',
                'venue'          => 'Old Trafford',
                'location'       => 'Manchester, England',
                'event_type'     => 'Football Match',
                'sport'          => 'Football',
                'team'           => 'Manchester United vs Liverpool',
                'event_date'     => Carbon::now()->addDays(30),
                'min_price'      => 220.00,
                'max_price'      => 280.50,
                'currency'       => 'GBP',
                'availability'   => 'available',
                'is_available'   => TRUE,
                'is_high_demand' => TRUE,
                'status'         => ScrapedTicket::STATUS_ACTIVE,
                'ticket_url'     => 'https://stubhub.co.uk/manchester-united-tickets/123',
                'search_keyword' => 'Manchester United Premier League Football',
                'metadata'       => [
                    'category'   => 'Premier League',
                    'match_type' => 'Home',
                    'importance' => 'High',
                    'section'    => 'South Stand',
                    'row'        => '10',
                ],
            ],
            [
                'platform'       => 'ticketmaster',
                'external_id'    => 'TM-ARS-CHE-002',
                'title'          => 'Arsenal vs Chelsea',
                'venue'          => 'Emirates Stadium',
                'location'       => 'London, England',
                'event_type'     => 'Football Match',
                'sport'          => 'Football',
                'team'           => 'Arsenal vs Chelsea',
                'event_date'     => Carbon::now()->addDays(45),
                'min_price'      => 150.00,
                'max_price'      => 210.75,
                'currency'       => 'GBP',
                'availability'   => 'available',
                'is_available'   => TRUE,
                'is_high_demand' => TRUE,
                'status'         => ScrapedTicket::STATUS_ACTIVE,
                'ticket_url'     => 'https://ticketmaster.co.uk/arsenal-chelsea-456',
                'search_keyword' => 'Arsenal Chelsea Premier League London Derby',
                'metadata'       => [
                    'category'   => 'Premier League',
                    'match_type' => 'Home',
                    'derby'      => TRUE,
                    'section'    => 'Clock End',
                    'row'        => '15',
                ],
            ],
            [
                'platform'       => 'viagogo',
                'external_id'    => 'VIA-RM-BAR-003',
                'title'          => 'Real Madrid vs Barcelona',
                'venue'          => 'Santiago Bernabéu',
                'location'       => 'Madrid, Spain',
                'event_type'     => 'Football Match',
                'sport'          => 'Football',
                'team'           => 'Real Madrid vs Barcelona',
                'event_date'     => Carbon::now()->addDays(60),
                'min_price'      => 450.00,
                'max_price'      => 520.00,
                'currency'       => 'EUR',
                'availability'   => 'available',
                'is_available'   => TRUE,
                'is_high_demand' => TRUE,
                'status'         => ScrapedTicket::STATUS_ACTIVE,
                'ticket_url'     => 'https://viagogo.com/real-madrid-barcelona-789',
                'search_keyword' => 'Real Madrid Barcelona El Clasico La Liga',
                'metadata'       => [
                    'category'   => 'La Liga',
                    'match_type' => 'El Clasico',
                    'importance' => 'Very High',
                    'section'    => 'Lateral Alto',
                    'row'        => '25',
                ],
            ],
            [
                'platform'       => 'stubhub',
                'external_id'    => 'STUB-LAL-GSW-004',
                'title'          => 'Los Angeles Lakers vs Golden State Warriors',
                'venue'          => 'Crypto.com Arena',
                'location'       => 'Los Angeles, CA',
                'event_type'     => 'Basketball Game',
                'sport'          => 'Basketball',
                'team'           => 'Lakers vs Warriors',
                'event_date'     => Carbon::now()->addDays(20),
                'min_price'      => 320.00,
                'max_price'      => 380.50,
                'currency'       => 'USD',
                'availability'   => 'available',
                'is_available'   => TRUE,
                'is_high_demand' => TRUE,
                'status'         => ScrapedTicket::STATUS_ACTIVE,
                'ticket_url'     => 'https://stubhub.com/lakers-warriors-101112',
                'search_keyword' => 'Lakers Warriors NBA Basketball Los Angeles',
                'metadata'       => [
                    'category' => 'NBA',
                    'sport'    => 'Basketball',
                    'rivalry'  => TRUE,
                    'section'  => 'Lower Bowl',
                    'row'      => '12',
                ],
            ],
            [
                'platform'       => 'ticketmaster',
                'external_id'    => 'TM-NYY-BOS-005',
                'title'          => 'New York Yankees vs Boston Red Sox',
                'venue'          => 'Yankee Stadium',
                'location'       => 'New York, NY',
                'event_type'     => 'Baseball Game',
                'sport'          => 'Baseball',
                'team'           => 'Yankees vs Red Sox',
                'event_date'     => Carbon::now()->addDays(25),
                'min_price'      => 125.00,
                'max_price'      => 145.75,
                'currency'       => 'USD',
                'availability'   => 'available',
                'is_available'   => TRUE,
                'is_high_demand' => FALSE,
                'status'         => ScrapedTicket::STATUS_ACTIVE,
                'ticket_url'     => 'https://ticketmaster.com/yankees-redsox-131415',
                'search_keyword' => 'Yankees Red Sox MLB Baseball New York',
                'metadata'       => [
                    'category' => 'MLB',
                    'sport'    => 'Baseball',
                    'rivalry'  => 'Yankees-Red Sox',
                    'section'  => 'Field Level',
                    'row'      => '8',
                ],
            ],
            [
                'platform'       => 'viagogo',
                'external_id'    => 'VIA-SB-2025-006',
                'title'          => 'Super Bowl LIX 2025',
                'venue'          => 'Caesars Superdome',
                'location'       => 'New Orleans, LA',
                'event_type'     => 'Championship Game',
                'sport'          => 'American Football',
                'team'           => 'TBD vs TBD',
                'event_date'     => Carbon::now()->addMonths(3),
                'min_price'      => 2500.00,
                'max_price'      => 2850.00,
                'currency'       => 'USD',
                'availability'   => 'available',
                'is_available'   => TRUE,
                'is_high_demand' => TRUE,
                'status'         => ScrapedTicket::STATUS_ACTIVE,
                'ticket_url'     => 'https://viagogo.com/super-bowl-161718',
                'search_keyword' => 'Super Bowl NFL Football Championship',
                'metadata'       => [
                    'category'   => 'NFL',
                    'sport'      => 'American Football',
                    'event_type' => 'Championship',
                    'importance' => 'Highest',
                    'section'    => 'Upper Deck',
                    'row'        => '35',
                ],
            ],
            [
                'platform'       => 'stubhub',
                'external_id'    => 'STUB-LIV-MCI-007',
                'title'          => 'Liverpool vs Manchester City',
                'venue'          => 'Anfield',
                'location'       => 'Liverpool, England',
                'event_type'     => 'Football Match',
                'sport'          => 'Football',
                'team'           => 'Liverpool vs Manchester City',
                'event_date'     => Carbon::now()->addDays(50),
                'min_price'      => 200.00,
                'max_price'      => 235.00,
                'currency'       => 'GBP',
                'availability'   => 'limited',
                'is_available'   => TRUE,
                'is_high_demand' => TRUE,
                'status'         => ScrapedTicket::STATUS_ACTIVE,
                'ticket_url'     => 'https://stubhub.co.uk/liverpool-city-192021',
                'search_keyword' => 'Liverpool Manchester City Premier League Title Race',
                'metadata'       => [
                    'category'   => 'Premier League',
                    'match_type' => 'Title Decider',
                    'atmosphere' => 'Electric',
                    'section'    => 'The Kop',
                    'row'        => '20',
                ],
            ],
        ];

        foreach ($events as $eventData) {
            ScrapedTicket::create($eventData);
        }

        $this->command->info('✓ Successfully created ' . count($events) . ' sample scraped tickets');
    }
}
