import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    "./resources/**/*.css",
  ],
  darkMode: 'class',
  theme: {
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      'desktop-lg': '1440px',
      'desktop-xl': '1920px',
    },
    extend: {
      colors: {
        // Minimal brand aliases for utility usage
        primary: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
          950: '#022c22',
        },
        secondary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
      },
      // Map design tokens to Tailwind theme
      fontFamily: {
        sans: ['var(--hdt-font-family-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        serif: ['var(--hdt-font-family-serif)', 'ui-serif', 'Georgia', 'serif'],
        mono: ['var(--hdt-font-family-mono)', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        'xs': 'var(--hdt-font-size-xs)',
        'sm': 'var(--hdt-font-size-sm)',
        'base': 'var(--hdt-font-size-base)',
        'lg': 'var(--hdt-font-size-lg)',
        'xl': 'var(--hdt-font-size-xl)',
        '2xl': 'var(--hdt-font-size-2xl)',
        '3xl': 'var(--hdt-font-size-3xl)',
        '4xl': 'var(--hdt-font-size-4xl)',
        '5xl': 'var(--hdt-font-size-5xl)',
        '6xl': 'var(--hdt-font-size-6xl)',
      },
      lineHeight: {
        'none': 'var(--hdt-line-height-none)',
        'tight': 'var(--hdt-line-height-tight)',
        'snug': 'var(--hdt-line-height-snug)',
        'normal': 'var(--hdt-line-height-normal)',
        'relaxed': 'var(--hdt-line-height-relaxed)',
        'loose': 'var(--hdt-line-height-loose)',
      },
      colors: {
        // HD Tickets brand colors using design tokens
        'hd-primary': {
          50: 'var(--hdt-color-primary-50)',
          100: 'var(--hdt-color-primary-100)',
          200: 'var(--hdt-color-primary-200)',
          300: 'var(--hdt-color-primary-300)',
          400: 'var(--hdt-color-primary-400)',
          500: 'var(--hdt-color-primary-500)',
          600: 'var(--hdt-color-primary-600)',
          700: 'var(--hdt-color-primary-700)',
          800: 'var(--hdt-color-primary-800)',
          900: 'var(--hdt-color-primary-900)',
          950: 'var(--hdt-color-primary-950)',
        },
        'hd-secondary': {
          50: 'var(--hdt-color-secondary-50)',
          100: 'var(--hdt-color-secondary-100)',
          200: 'var(--hdt-color-secondary-200)',
          300: 'var(--hdt-color-secondary-300)',
          400: 'var(--hdt-color-secondary-400)',
          500: 'var(--hdt-color-secondary-500)',
          600: 'var(--hdt-color-secondary-600)',
          700: 'var(--hdt-color-secondary-700)',
          800: 'var(--hdt-color-secondary-800)',
          900: 'var(--hdt-color-secondary-900)',
          950: 'var(--hdt-color-secondary-950)',
        },
        'hd-success': {
          50: 'var(--hdt-color-success-50)',
          100: 'var(--hdt-color-success-100)',
          200: 'var(--hdt-color-success-200)',
          300: 'var(--hdt-color-success-300)',
          400: 'var(--hdt-color-success-400)',
          500: 'var(--hdt-color-success-500)',
          600: 'var(--hdt-color-success-600)',
          700: 'var(--hdt-color-success-700)',
          800: 'var(--hdt-color-success-800)',
          900: 'var(--hdt-color-success-900)',
          950: 'var(--hdt-color-success-950)',
        },
        'hd-warning': {
          50: 'var(--hdt-color-warning-50)',
          100: 'var(--hdt-color-warning-100)',
          200: 'var(--hdt-color-warning-200)',
          300: 'var(--hdt-color-warning-300)',
          400: 'var(--hdt-color-warning-400)',
          500: 'var(--hdt-color-warning-500)',
          600: 'var(--hdt-color-warning-600)',
          700: 'var(--hdt-color-warning-700)',
          800: 'var(--hdt-color-warning-800)',
          900: 'var(--hdt-color-warning-900)',
          950: 'var(--hdt-color-warning-950)',
        },
        'hd-danger': {
          50: 'var(--hdt-color-danger-50)',
          100: 'var(--hdt-color-danger-100)',
          200: 'var(--hdt-color-danger-200)',
          300: 'var(--hdt-color-danger-300)',
          400: 'var(--hdt-color-danger-400)',
          500: 'var(--hdt-color-danger-500)',
          600: 'var(--hdt-color-danger-600)',
          700: 'var(--hdt-color-danger-700)',
          800: 'var(--hdt-color-danger-800)',
          900: 'var(--hdt-color-danger-900)',
          950: 'var(--hdt-color-danger-950)',
        },
        'hd-info': {
          50: 'var(--hdt-color-info-50)',
          100: 'var(--hdt-color-info-100)',
          200: 'var(--hdt-color-info-200)',
          300: 'var(--hdt-color-info-300)',
          400: 'var(--hdt-color-info-400)',
          500: 'var(--hdt-color-info-500)',
          600: 'var(--hdt-color-info-600)',
          700: 'var(--hdt-color-info-700)',
          800: 'var(--hdt-color-info-800)',
          900: 'var(--hdt-color-info-900)',
          950: 'var(--hdt-color-info-950)',
        },
        'hd-gray': {
          50: 'var(--hdt-gray-50)',
          100: 'var(--hdt-gray-100)',
          200: 'var(--hdt-gray-200)',
          300: 'var(--hdt-gray-300)',
          400: 'var(--hdt-gray-400)',
          500: 'var(--hdt-gray-500)',
          600: 'var(--hdt-gray-600)',
          700: 'var(--hdt-gray-700)',
          800: 'var(--hdt-gray-800)',
          900: 'var(--hdt-gray-900)',
          950: 'var(--hdt-gray-950)',
        },
        // Semantic colors
        'surface': {
          primary: 'var(--hdt-color-surface-primary)',
          secondary: 'var(--hdt-color-surface-secondary)',
          tertiary: 'var(--hdt-color-surface-tertiary)',
          inverse: 'var(--hdt-color-surface-inverse)',
        },
        'text': {
          primary: 'var(--hdt-color-text-primary)',
          secondary: 'var(--hdt-color-text-secondary)',
          tertiary: 'var(--hdt-color-text-tertiary)',
          quaternary: 'var(--hdt-color-text-quaternary)',
          inverse: 'var(--hdt-color-text-inverse)',
        },
        'border': {
          primary: 'var(--hdt-color-border-primary)',
          secondary: 'var(--hdt-color-border-secondary)',
          tertiary: 'var(--hdt-color-border-tertiary)',
          inverse: 'var(--hdt-color-border-inverse)',
        },
        // Role colors
        'role': {
          primary: 'var(--hdt-role-primary)',
          secondary: 'var(--hdt-role-secondary)',
          surface: 'var(--hdt-role-surface)',
        },
        // Status colors
        'status': {
          online: 'var(--hdt-color-status-online)',
          offline: 'var(--hdt-color-status-offline)',
          pending: 'var(--hdt-color-status-pending)',
          error: 'var(--hdt-color-status-error)',
        },
      },
      spacing: {
        'px': 'var(--hdt-spacing-px)',
        '0': 'var(--hdt-spacing-0)',
        '0.5': 'var(--hdt-spacing-0-5)',
        '1': 'var(--hdt-spacing-1)',
        '1.5': 'var(--hdt-spacing-1-5)',
        '2': 'var(--hdt-spacing-2)',
        '2.5': 'var(--hdt-spacing-2-5)',
        '3': 'var(--hdt-spacing-3)',
        '3.5': 'var(--hdt-spacing-3-5)',
        '4': 'var(--hdt-spacing-4)',
        '5': 'var(--hdt-spacing-5)',
        '6': 'var(--hdt-spacing-6)',
        '7': 'var(--hdt-spacing-7)',
        '8': 'var(--hdt-spacing-8)',
        '9': 'var(--hdt-spacing-9)',
        '10': 'var(--hdt-spacing-10)',
        '11': 'var(--hdt-spacing-11)',
        '12': 'var(--hdt-spacing-12)',
        '14': 'var(--hdt-spacing-14)',
        '16': 'var(--hdt-spacing-16)',
        '20': 'var(--hdt-spacing-20)',
        '24': 'var(--hdt-spacing-24)',
        '28': 'var(--hdt-spacing-28)',
        '32': 'var(--hdt-spacing-32)',
      },
      borderRadius: {
        'none': 'var(--hdt-radius-none)',
        'sm': 'var(--hdt-radius-sm)',
        'DEFAULT': 'var(--hdt-radius-base)',
        'md': 'var(--hdt-radius-md)',
        'lg': 'var(--hdt-radius-lg)',
        'xl': 'var(--hdt-radius-xl)',
        '2xl': 'var(--hdt-radius-2xl)',
        '3xl': 'var(--hdt-radius-3xl)',
        'full': 'var(--hdt-radius-full)',
      },
      boxShadow: {
        'xs': 'var(--hdt-shadow-xs)',
        'sm': 'var(--hdt-shadow-sm)',
        'DEFAULT': 'var(--hdt-shadow-base)',
        'md': 'var(--hdt-shadow-md)',
        'lg': 'var(--hdt-shadow-lg)',
        'xl': 'var(--hdt-shadow-xl)',
        '2xl': 'var(--hdt-shadow-2xl)',
        'inner': 'var(--hdt-shadow-inner)',
      },
      transitionDuration: {
        '75': 'var(--hdt-duration-75)',
        '100': 'var(--hdt-duration-100)',
        '150': 'var(--hdt-duration-150)',
        '200': 'var(--hdt-duration-200)',
        '300': 'var(--hdt-duration-300)',
        '500': 'var(--hdt-duration-500)',
        '700': 'var(--hdt-duration-700)',
        '1000': 'var(--hdt-duration-1000)',
      },
      transitionTimingFunction: {
        'linear': 'var(--hdt-ease-linear)',
        'in': 'var(--hdt-ease-in)',
        'out': 'var(--hdt-ease-out)',
        'in-out': 'var(--hdt-ease-in-out)',
      },
    },
  },
  // Safelist important classes to prevent purging
  safelist: [
    // Role layout classes
    'admin-layout',
    'agent-layout',
    'customer-layout',
    'scraper-layout',
    // Navigation active states
    'nav-item--active',
    'sidebar-item--active',
    // Theme classes
    'dark',
    'light',
    // Component state classes
    'hdt-button--primary',
    'hdt-button--secondary',
    'hdt-button--success',
    'hdt-button--warning',
    'hdt-button--danger',
    'hdt-button--info',
    'hdt-button--ghost',
    'hdt-card--elevated',
    'hdt-card--flat',
    'hdt-badge--success',
    'hdt-badge--warning',
    'hdt-badge--danger',
    'hdt-badge--info',
    'hdt-input--error',
    'hdt-input--disabled',
    'hdt-input--readonly',
    // Status indicators
    'status-online',
    'status-offline',
    'status-pending',
    'status-error',
    // Responsive layout classes
    'layout-grid',
    'layout-header',
    'layout-sidebar',
    'layout-main',
    'layout-footer',
  ],
  plugins: [
    // Custom plugin for design system utilities
    function ({ addUtilities, addComponents }) {
      // Add custom utilities that complement our design tokens
      addUtilities({
        '.content-wrapper': {
          'max-width': '1200px',
          'margin-left': 'auto',
          'margin-right': 'auto',
          'padding-left': 'var(--hdt-spacing-4)',
          'padding-right': 'var(--hdt-spacing-4)',
          '@screen md': {
            'padding-left': 'var(--hdt-spacing-6)',
            'padding-right': 'var(--hdt-spacing-6)',
          },
          '@screen lg': {
            'padding-left': 'var(--hdt-spacing-8)',
            'padding-right': 'var(--hdt-spacing-8)',
          },
        },
        '.main-section': {
          'padding-top': 'var(--hdt-spacing-6)',
          'padding-bottom': 'var(--hdt-spacing-6)',
          '@screen md': {
            'padding-top': 'var(--hdt-spacing-8)',
            'padding-bottom': 'var(--hdt-spacing-8)',
          },
          '@screen lg': {
            'padding-top': 'var(--hdt-spacing-12)',
            'padding-bottom': 'var(--hdt-spacing-12)',
          },
        },
        '.card-grid': {
          'display': 'grid',
          'gap': 'var(--hdt-spacing-6)',
          'grid-template-columns': '1fr',
          '@screen md': {
            'grid-template-columns': 'repeat(2, 1fr)',
          },
          '@screen lg': {
            'grid-template-columns': 'repeat(3, 1fr)',
          },
        },
      });

      // Add base component styles
      addComponents({
        '.hdt-focus-ring': {
          'outline': '2px solid var(--hdt-color-focus-ring)',
          'outline-offset': '2px',
        },
        '.hdt-transition': {
          'transition-property': 'color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
          'transition-timing-function': 'var(--hdt-ease-in-out)',
          'transition-duration': 'var(--hdt-duration-150)',
        },
      });
    },
  ],
}
tooltip: 60,
      },
fontFamily: {
  sans: ['Plus Jakarta Sans', 'Inter', 'ui-sans-serif', 'system-ui'],
    mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular'],
      },
colors: {
  // HD Tickets Brand Colors - Sports Theme
  primary: {
    50: '#eff6ff',
      100: '#dbeafe',
        200: '#bfdbfe',
          300: '#93c5fd',
            400: '#60a5fa',
              500: '#3b82f6', // HD Blue
                600: '#2563eb',
                  700: '#1d4ed8',
                    800: '#1e40af',
                      900: '#1e3a8a',
                        950: '#172554',
        },

  // HD Tickets Sports-themed Colors
  'hd-blue': {
    50: '#eff6ff',
      100: '#dbeafe',
        200: '#bfdbfe',
          300: '#93c5fd',
            400: '#60a5fa',
              500: '#3b82f6',
                600: '#2563eb',
                  700: '#1d4ed8',
                    800: '#1e40af',
                      900: '#1e3a8a',
        },

  'pitch-green': {
    50: '#f0fdf4',
      100: '#dcfce7',
        200: '#bbf7d0',
          300: '#86efac',
            400: '#4ade80',
              500: '#22c55e', // Stadium Grass
                600: '#16a34a',
                  700: '#15803d',
                    800: '#166534',
                      900: '#14532d',
        },

  'matchday-gold': {
    50: '#fffbeb',
      100: '#fef3c7',
        200: '#fde68a',
          300: '#fcd34d',
            400: '#fbbf24', // Stadium Lights
              500: '#f59e0b',
                600: '#d97706',
                  700: '#b45309',
                    800: '#92400e',
                      900: '#78350f',
        },

  'stadium-gray': {
    50: '#f9fafb',
      100: '#f3f4f6',
        200: '#e5e7eb',
          300: '#d1d5db',
            400: '#9ca3af',
              500: '#6b7280',
                600: '#4b5563',
                  700: '#374151',
                    800: '#1f2937',
                      900: '#111827',
        },

  'chalk-white': {
    50: '#ffffff',
      100: '#fefefe',
        200: '#fefefe',
          300: '#fdfdfd',
            400: '#fcfcfc',
              500: '#fafafa',
                600: '#f5f5f5',
                  700: '#eeeeee',
                    800: '#e0e0e0',
                      900: '#bdbdbd',
        },
  secondary: {
    50: '#f0f9ff',
      100: '#e0f2fe',
        200: '#bae6fd',
          300: '#7dd3fc',
            400: '#38bdf8',
              500: '#0ea5e9',
                600: '#0284c7',
                  700: '#0369a1',
                    800: '#075985',
                      900: '#0c4a6e',
                        950: '#082f49',
        },
  success: {
    50: '#f0fdf4',
      100: '#dcfce7',
        200: '#bbf7d0',
          300: '#86efac',
            400: '#4ade80',
              500: '#22c55e',
                600: '#16a34a',
                  700: '#15803d',
                    800: '#166534',
                      900: '#14532d',
                        950: '#052e16',
        },
  warning: {
    50: '#fffbeb',
      100: '#fef3c7',
        200: '#fde68a',
          300: '#fcd34d',
            400: '#fbbf24',
              500: '#f59e0b',
                600: '#d97706',
                  700: '#b45309',
                    800: '#92400e',
                      900: '#78350f',
                        950: '#451a03',
        },
  error: {
    50: '#fef2f2',
      100: '#fee2e2',
        200: '#fecaca',
          300: '#fca5a5',
            400: '#f87171',
              500: '#ef4444',
                600: '#dc2626',
                  700: '#b91c1c',
                    800: '#991b1b',
                      900: '#7f1d1d',
                        950: '#450a0a',
        },
  // Stadium-inspired colors
  stadium: {
    grass: '#22c55e',
      field: '#16a34a',
        track: '#dc2626',
          scoreboard: '#1e40af',
            lights: '#fbbf24',
        }
},
animation: {
  'fade-in': 'fadeIn 0.5s ease-in-out',
    'slide-up': 'slideUp 0.3s ease-out',
      'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
          'bounce-gentle': 'bounceGentle 2s infinite',
            'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
              'float': 'float 6s ease-in-out infinite',
                'glow': 'glow 2s ease-in-out infinite alternate',
                  'step-progress': 'stepProgress 0.3s ease-out',
                    'code-input': 'codeInput 0.2s ease-out',
                      'success-check': 'successCheck 0.5s ease-out',
      },
keyframes: {
  fadeIn: {
    '0%': { opacity: '0', transform: 'translateY(10px)' },
    '100%': { opacity: '1', transform: 'translateY(0)' },
  },
  slideUp: {
    '0%': { transform: 'translateY(100%)', opacity: '0' },
    '100%': { transform: 'translateY(0)', opacity: '1' },
  },
  slideDown: {
    '0%': { transform: 'translateY(-100%)', opacity: '0' },
    '100%': { transform: 'translateY(0)', opacity: '1' },
  },
  scaleIn: {
    '0%': { transform: 'scale(0.9)', opacity: '0' },
    '100%': { transform: 'scale(1)', opacity: '1' },
  },
  bounceGentle: {
    '0%, 100%': { transform: 'translateY(0)' },
    '50%': { transform: 'translateY(-5px)' },
  },
  float: {
    '0%, 100%': { transform: 'translateY(0px)' },
    '50%': { transform: 'translateY(-10px)' },
  },
  glow: {
    '0%': { boxShadow: '0 0 5px rgb(59 130 246 / 0.5)' },
    '100%': { boxShadow: '0 0 20px rgb(59 130 246 / 0.8)' },
  },
  stepProgress: {
    '0%': { transform: 'scale(0.8)', opacity: '0' },
    '50%': { transform: 'scale(1.05)', opacity: '1' },
    '100%': { transform: 'scale(1)', opacity: '1' },
  },
  codeInput: {
    '0%': { transform: 'scale(1)', borderColor: 'rgb(209 213 219)' },
    '50%': { transform: 'scale(1.05)', borderColor: 'rgb(59 130 246)' },
    '100%': { transform: 'scale(1)', borderColor: 'rgb(34 197 94)' },
  },
  successCheck: {
    '0%': { transform: 'scale(0) rotate(0deg)', opacity: '0' },
    '50%': { transform: 'scale(1.2) rotate(180deg)', opacity: '1' },
    '100%': { transform: 'scale(1) rotate(360deg)', opacity: '1' },
  },
},
backdropBlur: {
  xs: '2px',
      },
backgroundImage: {
  'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
    'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      'stadium-field': 'linear-gradient(135deg, #16a34a 0%, #22c55e 100%)',
        'stadium-sky': 'linear-gradient(135deg, #1e40af 0%, #3b82f6 35%, #8b5cf6 70%, #1e40af 100%)',
      },
spacing: {
  '18': '4.5rem',
    '22': '5.5rem',
      '88': '22rem',
        '92': '23rem',
          '96': '24rem',
            '128': '32rem',
              // Touch-friendly minimum tap targets
              'touch-sm': '2.75rem', // 44px minimum for mobile
                'touch-md': '3rem',    // 48px comfortable
                  'touch-lg': '3.5rem',  // 56px large
                    // Form-specific spacing
                    'form-gap': '1.5rem',  // 24px between form sections
                      'form-row': '1rem',    // 16px between form rows
      },
borderRadius: {
  '4xl': '2rem',
    '5xl': '2.5rem',
      },
boxShadow: {
  'glow': '0 0 20px rgba(59, 130, 246, 0.4)',
    'glow-lg': '0 0 40px rgba(59, 130, 246, 0.6)',
      'stadium': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        // Enhanced focus shadows for accessibility
        'focus-ring': '0 0 0 3px rgba(59, 130, 246, 0.3)',
          'focus-ring-error': '0 0 0 3px rgba(239, 68, 68, 0.3)',
            'focus-ring-success': '0 0 0 3px rgba(34, 197, 94, 0.3)',
              // Form-specific shadows
              'form-focus': '0 0 0 2px rgba(59, 130, 246, 0.2), 0 0 0 4px rgba(59, 130, 246, 0.1)',
                'step-active': '0 4px 12px rgba(59, 130, 246, 0.25)',
                  'step-complete': '0 4px 12px rgba(34, 197, 94, 0.25)',
      },
blur: {
  xs: '2px',
      },
    },
  },
plugins: [
  forms,
  typography,
],
};
