<?php declare(strict_types=1);

namespace Database\Factories;

use App\Models\PaymentPlan;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<PaymentPlan>
 */
class PaymentPlanFactory extends Factory
{
    protected $model = PaymentPlan::class;

    public function definition(): array
    {
        static $order = 1;

        return [
            'name' => 'Plan ' . $order,
            'slug' => 'plan-' . $order,
            'description' => 'Autogenerated test payment plan',
            'price' => 29.99,
            'billing_cycle' => 'monthly',
            'features' => json_encode(['feature a','feature b']),
            'max_tickets_per_month' => 100,
            'max_concurrent_purchases' => 2,
            'max_platforms' => 5,
            'priority_support' => false,
            'advanced_analytics' => false,
            'automated_purchasing' => false,
            'is_active' => true,
            'sort_order' => $order++,
            'stripe_price_id' => null,
        ];
    }
}